### ISSUE TITLE
bCNC ?

### ISSUE THREAD

**Issue by iconmix** [Billiam/cncjs-pendant-streamdeck#10]
hello...
this is not an issue, but just a question :  
do you know bCNC ?  https://github.com/vlachoudis/bCNC
is possible for you to adjust your code to working with bCNC and your perfect interface ?
on Raspberry, bCNC work fastest than cncjs....so if you could....

anyway thanks you for all

**Comment by Billiam** [comment]
Hi, no plans to port this to bCNC. Sorry!
