### ISSUE TITLE
Feedrate, spindle speed remain locked out during operation.

### ISSUE THREAD

**Issue by unstable-deadlock** [Billiam/cncjs-pendant-streamdeck#11]
![C2F8F86B-E677-485D-8150-46D0456E2637](https://user-images.githubusercontent.com/8198523/190521148-c70eae40-230b-410f-9c29-05ec6129d555.jpeg)

**Comment by BrashEndeavours** [comment]
Wait out. Might be a config issue.

**Comment by Billiam** [comment]
Can you confirm which version you're using? This looks like a duplicate of #5 (which should currently be fixed).

**Comment by unstable-deadlock** [comment]
I thought the same thing. 
0.4.3

**Comment by Billiam** [comment]
Nothing changed between 0.4.3 that would affect it, but can you try 0.5.0 (just released)?

You can verify the running version after installation with `cncjs-pendant-streamdeck -V`

Does your configuration validate correctly at https://billiam.github.io/cncjs-pendant-streamdeck/validator/ ?

I'm not seeing this issue in 0.4.3 or 0.5.0.

Is it possible it's an issue with your current configuration?

**Comment by unstable-deadlock** [comment]
Local configuration issue. 
Apologies, closing.
