### ISSUE TITLE
improved functions

### ISSUE THREAD

**Issue by metropolicon** [Billiam/cncjs-pendant-streamdeck#12]
Hi....
sorry it's not an issue but don't know how to contact you.....

i've forked your streamdeck and add some good capabilities if you want to include in your :

- in gcode preview, now , we see machine position on gcode picture like in cncjs interface
<img width="30%" src="https://i.imgur.com/VFkncaC.jpg" />
- added function to move cnc position at clic position grid and  can now show machine size 
<img width="30%" src="https://i.imgur.com/43jlwHl.jpg" />
-  added messagebox information
<img width="30%" src="https://i.imgur.com/7Ob4AX6.jpg" />

may be some bugs but if you want to test it :
<a href="https://github.com/metropolicon/cncjs-pendant-streamdeck">https://github.com/metropolicon/cncjs-pendant-streamdeck</a>
Sorry i'm french, so , some labels  are in french.......
anyway thanks for your great job ! ;)

**Comment by Billiam** [comment]
Looks neat! I'm not going to add the 'click to move' feature, because I'd like to keep feature compatibility between the web and stream deck versions, but the current machine position is a good idea. Thanks!
