### ISSUE TITLE
How to use it in Windows 11 ?

### ISSUE THREAD

**Issue by DomML** [Billiam/cncjs-pendant-streamdeck#14]
Hi,
I'm tryig to install the pendant on windows, however, everytime I change the .cncrc file to add the path toward it, it break CNCJS.
Everything come to normal if I reverse tot he original .cncrc.

```
{
    "state": {
        "checkForUpdates": true,
        "controller": {
            "exception": {
                "ignoreErrors": false
            }
        }
    },
    "secret": "$2a$10$/o78W5zJWNMOCIDoP0EX1u",
    "mountPoints": [
        {
          "route": "/grid",
          "target": "C:\Users\Nouveau\cncjs-pendant-streamdeck"
        }
      ]
}
```

**Comment by metropolicon** [comment]
replace `"target": "C:\Users\Nouveau\cncjs-pendant-streamdeck"`
by `"target": "C:\\Users\\Nouveau\\cncjs-pendant-streamdeck"`

**Comment by DomML** [comment]
It works, thank you!
