### ISSUE TITLE
Compatible Devices

### ISSUE THREAD

**Issue by 3kmch** [Billiam/cncjs-pendant-streamdeck#16]
To get started, I set up the web version yesterday (with help from @manuelmeister) and I'm super happy with the result. Thanks @Billiam for sharing this repository :)

Do you know if streamdecks like https://www.miraboxfactory.com/lcd-keyboard/566886 will work with your code? Do you have any feedback from users?

**Comment by Billiam** [comment]
The lower level library that cncjs-pendant-streamdeck uses to communicate with the stream deck does not support non-elgato devices at this time (https://github.com/Julusian/node-elgato-stream-deck/issues/107), so these will not work unfortunately.

**Comment by 3kmch** [comment]
OK and thanks for your feedback :)
