### ISSUE TITLE
Web UI Squashed on Firefox 103.0.1

### ISSUE THREAD

**Issue by unstable-deadlock** [Billiam/cncjs-pendant-streamdeck#2]
When loading the most current release in FF, the UI is squashed in the top of the browser viewport.

![image](https://user-images.githubusercontent.com/8198523/183227979-bb01057a-a1b4-4e7d-99c1-25cff0c23a0b.png)

**Comment by Billiam** [comment]
There was a little CSS typo that affected the HTML height (https://github.com/Billiam/cncjs-pendant-streamdeck/commit/045455cb576ac6a1b430f3804304e4b2a6e04231)

Should be fixed in [0.2.2](https://github.com/Billiam/cncjs-pendant-streamdeck/releases/tag/0.2.2)
