### ISSUE TITLE
Speed changes on pendant disabled during program

### ISSUE THREAD

**Issue by unstable-deadlock** [Billiam/cncjs-pendant-streamdeck#5]
During the execution of a gcode program, the buttons to alter the values speed/feed/spindle are greyed out.

![136613A4-CD76-44B8-9B3D-2B60A577ED75](https://user-images.githubusercontent.com/8198523/183525157-0c0a384a-a92a-4f70-995e-92935278d3dd.jpeg)

they are available in the web ui however.

**Comment by Billiam** [comment]
Thanks! This has been fixed in https://github.com/Billiam/cncjs-pendant-streamdeck/commit/0d28547789a4d98ad5ab6328c5accbfd0d27806e
