### ISSUE TITLE
CNC position updates are cut off

### ISSUE THREAD

**Issue by unstable-deadlock** [Billiam/cncjs-pendant-streamdeck#6]
The CNC position status screen text is truncated. Adjusting the settings.json font size only seems to effect the web UI.

![87279B90-BA62-4B56-BCE1-D5690D158EB4](https://user-images.githubusercontent.com/8198523/184056185-750e924e-fdf5-46a3-a2f9-5a024d1d0a08.jpeg)

**Comment by Billiam** [comment]
The stream deck process doesn't do any automatic font scaling or anything, so it's kind of up to you to either use small text or carefully curate the text content itself to keep its width/height to a minimum for your needs.

Are you sure your font size setting isn't affecting the stream deck display? If so, that's a bug. Note that you'll need to restart the process after making any configuration changes.

My personal preferences is to use a smaller pixel font, which looks like this: 
![](https://github.com/Billiam/cncjs-pendant-streamdeck/raw/main/assets/streamdeck.jpg)

My config uses:

```json
"ui": {
    "font": "ProggyTinyTT",
    "fontSize": 16,
    "lineHeight": 0.75,
}
```
from [proggy fonts](http://www.proggyfonts.net/index.php?menu=download)

**Comment by Billiam** [comment]
I'm planning (at some point) to add a general override for the UI config section that would only affect the stream deck to make sharing a single config a bit easier.

**Comment by unstable-deadlock** [comment]
My fault. It was the line height!
Thank you for sharing your configuration.
