### ISSUE TITLE
"if" fonction seem to not work....

### ISSUE THREAD

**Issue by iconmix** [Billiam/cncjs-pendant-streamdeck#7]
hello.....
this is my configuration :
CNC homemade + arduino UNO + raspberry pi 3B+ with 7" LCD HDMI TOUCH screen
CNCJS work perfectly on RPi.
MachinePosition button never showing :(
![CNCjs Grid UI - 192 168 1 20](https://user-images.githubusercontent.com/26572446/184581098-3c95d99c-e198-4179-a130-8dbf040fef91.png)

"machinePosition": {
      "actions": [
        {
          "action": "toggleUserFlag",
          "arguments": ["showAbsolutePosition"]
        }
      ],
      "bgColor": 8,
      "if": "ui.userFlags.showAbsolutePosition !== true",
      "text": "--{{cnc.workflowState}}--\nMachine Pos\n{{cnc.displayMpos}}",
      "textAlignment": "left"
    },

I've tried many condition like "cnc.idle","cnc.alarm","ui.web" but "if" block always the button....
with "if" : "cnc.idle" 
If i remove "if" line, the button appears and i can see "cnc.idle" is true....
"machinePosition": {
      "actions": [
        {
          "action": "toggleUserFlag",
          "arguments": ["showAbsolutePosition"]
        }
      ],
      "bgColor": 8,
      "text": "{{cnc.idle}}\n{{cnc.workflowState}}--\nMachine Pos\n{{cnc.displayMpos}}",
      "textAlignment": "left"
    },

![002 - CNCjs Grid UI - 192 168 1 20](https://user-images.githubusercontent.com/26572446/184581131-6db0a3bf-e6d3-437c-bb7b-51cfa84719fb.png)

So i think the "if" function don't work for me :(

Any clue about this ?

And, under windows or linux, how to build your package ? i've installed nodejs, vue, vite but always error at build :(
I'm sure i don't do the right thing .....
Thanks in advance

**Comment by Billiam** [comment]
There's an issue with the build system for the web version that I think is affecting you here.

I believe I have a fix for it that I'll be pushing out soon

**Comment by iconmix** [comment]
> There's an issue with the build system for the web version that I think is affecting you here.
> 
> I believe I have a fix for it that I'll be pushing out soon

Thank you....
I'm  a noob in nodejs dev :(  sorry

**Comment by Billiam** [comment]
This should be fixed in [0.2.5](https://github.com/Billiam/cncjs-pendant-streamdeck/releases/tag/0.2.5)
