### ISSUE TITLE
cncjs "command"

### ISSUE THREAD

**Issue by iconmix** [Billiam/cncjs-pendant-streamdeck#8]
Hi...
definitively the best pendant for cncjs, streamdeck can call cncjs command ?
in cncjs, you can define your own command like that in cncrc.cfg : 

"commands": [
        {
            "title": "Update (root user)",
            "commands": "sudo npm install -g cncjs@latest --unsafe-perm; pkill -f cncjs"
        },
        {
            "title": "Update (non-root user)",
            "commands": "npm install -g cncjs@latest; pkill -f cncjs"
        },
        {
            "title": "Reboot",
            "commands": "sudo /sbin/reboot"
        },
        {
            "title": "Shutdown",
            "commands": "sudo /sbin/shutdown"
        }
    ],`

But i can't find how to call from streamdeck button like for macros
![Image1](https://user-images.githubusercontent.com/26572446/186433733-6d21fe16-a08b-4616-8b01-bd88f09be810.jpg)
....
Is possible or not ?
Anyway....Thanks for your great job !!!

**Comment by Billiam** [comment]
This isn't possible in the current version, but I'll see about getting it added.

**Comment by iconmix** [comment]
thank you !

**Comment by Billiam** [comment]
Support for commands added in [0.4.1](https://github.com/Billiam/cncjs-pendant-streamdeck/releases/tag/0.4.1)

Documentation for this action can be found here: https://billiam.github.io/cncjs-pendant-streamdeck/docs/actions/#command
