### ISSUE TITLE
filelist seem got problem

### ISSUE THREAD

**Issue by iconmix** [Billiam/cncjs-pendant-streamdeck#9]
Hello....
Thanks for "command" action .....really nice !!!!!

I've a problem with filelist .......
first screen :
![1](https://user-images.githubusercontent.com/26572446/187019450-7e393b6b-2788-4617-8862-3415462c78c5.jpg)

then i select gcodes directory who contain 21 files and as you can see the down arrow is not present....:( : 
![2](https://user-images.githubusercontent.com/26572446/187019494-d632d32c-8c1d-4552-bbaf-ad3f188a75b3.jpg)

i click on Back button and return by clicking on filelist button (loadGcode) : 
![3](https://user-images.githubusercontent.com/26572446/187019571-24018766-4212-4d98-ab6a-d228018a6d31.jpg)

Now i get down arrow but if i click on it, nothing change execpt the 2nd button (yellow circle on picture)
![4](https://user-images.githubusercontent.com/26572446/187019615-f06f91a1-52d3-438c-8520-ed45180c9c67.jpg)

It seem not refeshing all buttons.....
Any clue ?

And thanks again for your excellent work !!!!

**Comment by Billiam** [comment]
That doesn't look right :smile:

What browser are you using? What operating system?

Do you see any errors in the javascript console?

Is your configuration [valid](https://billiam.github.io/cncjs-pendant-streamdeck/validator/)?

**Comment by iconmix** [comment]
hi...
all is working except filelist view.....

**my config : 
_Raspberry pi 4 on chromium brower with 7inch screen_ 
and 
_PC Windows 10 with firefox.....(same problem)_**

**Tested my config.json with your validator ....seem ok.....**
[config.zip](https://github.com/Billiam/cncjs-pendant-streamdeck/files/9438434/config.zip)


**console output (sorry i'm french ;) ) :** 

`unreachable code after return statement index.js:14496:6

Connected to port /dev/ttyACM0 index.js:17756:15

unreachable code after return statement index.js:14496:6

Certains cookies utilisent incorrectement l’attribut recommandé « SameSite » 3
Le cookie « lang » n’a pas de valeur d’attribut « SameSite » appropriée. Bientôt, les cookies dont l’attribut « SameSite » est manquant ou défini avec une valeur invalide seront traités comme « Lax ». Cela signifie que le cookie ne sera plus envoyé dans des contextes tiers. Si votre application dépend de la disponibilité de ce cookie dans de tels contextes, veuillez lui ajouter l’attribut « SameSite=None ». Pour en savoir plus sur l’attribut « SameSite », consultez https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite files

Le cookie « lang » n’a pas de valeur d’attribut « SameSite » appropriée. Bientôt, les cookies dont l’attribut « SameSite » est manquant ou défini avec une valeur invalide seront traités comme « Lax ». Cela signifie que le cookie ne sera plus envoyé dans des contextes tiers. Si votre application dépend de la disponibilité de ce cookie dans de tels contextes, veuillez lui ajouter l’attribut « SameSite=None ». Pour en savoir plus sur l’attribut « SameSite », consultez https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite files

Le cookie « lang » n’a pas de valeur d’attribut « SameSite » appropriée. Bientôt, les cookies dont l’attribut « SameSite » est manquant ou défini avec une valeur invalide seront traités comme « Lax ». Cela signifie que le cookie ne sera plus envoyé dans des contextes tiers. Si votre application dépend de la disponibilité de ce cookie dans de tels contextes, veuillez lui ajouter l’attribut « SameSite=None ». Pour en savoir plus sur l’attribut « SameSite », consultez https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 files

`
### 
Thanks !

**Comment by Billiam** [comment]
Thanks! This has been fixed in [0.4.3](https://github.com/Billiam/cncjs-pendant-streamdeck/releases/tag/0.4.3)

**Comment by iconmix** [comment]
big thanks ! Now it's perfect :)
